version: '2'
services:
    government_system-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/government_system/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=government_system
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
